# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 791539ea8ae60c6da05ac1acb39240b1adee739e4bb032e888eeb4629b490bc8a646f3fab4e3c5050d73d04aaf50df4aabf6e4f6d04b2324aa0fd08e0ae5bbe1

test:
  secret_key_base: 4d37d0c7cf838aa70d88fc427d8c0488a1914886c38835329734dd8d06a273624681063e2eb9c8f72ab90698689904c12f4e6f554fe86beb19fc84f71bdb0f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
